version: "3"

services:
  web:
    build: express-server
    ports:
    - "8080:8080"
    networks:
    - beingzero
    environment:
    - "MONGO_SERVER=mongodb"
    - "MONGO_PORT=27017"
    - "MONGO_DBNAME=dockerAppDb"
    - "WEB_PORT=8080"
    links:
      - mongodb
  
  mongodb:
    build: mongo-server
    ports:
    - "27018:27017"
    networks:
    - beingzero

networks:
  beingzero: